import { SchoolConfig, NewsArticle } from '../types';
import { DEFAULT_THEME_CONFIG } from './themePresets';
import { DEFAULT_APPS_SCRIPT_WEB_APP_URL, DEFAULT_APPS_SCRIPT_FOLDER_ID } from './googleAppsScript';

export const DEFAULT_SCHOOL_CONFIG: SchoolConfig = {
  adminPassword: 'smpn1bks',
  identity: {
    name: 'SMP Negeri 1 Bengkalis',
    shortName: 'SMPN 1 Bengkalis',
    tagline: 'Mewujudkan Insan Beriman, Berakhlak Mulia, Cerdas, Terampil, dan Berbudaya Lingkungan',
    npsn: '10495146',
    akreditasi: 'Akreditasi A (Unggul)',
    logoUrl: '',
    faviconUrl: '',
    tickerEnabled: false,
    tickerText: '',
    accreditationTickerEnabled: true,
    accreditationTickerText: 'Status Akreditasi A (Unggul) — Sertifikasi Resmi BAN-S/M • Nomor Pokok Sekolah Nasional (NPSN): 10495146 • Peringkat Akreditasi Tertinggi Standar Mutu Pendidikan Nasional • SMP Negeri 1 Bengkalis — Unggul, Berkarakter & Berprestasi',
    accreditationTickerSpeed: 'normal',
    primaryColor: 'blue',
  },
  importantAnnouncement: {
    enabled: true,
    badge: 'INFO PENTING',
    text: '📢 PEMBERITAHUAN KABUT ASAP & PENYESUAIAN KBM: Menindaklanjuti Surat Edaran Resmi, seluruh kegiatan belajar tatap muka sementara dialihkan secara Daring (PJJ) dari rumah mulai tanggal 9 - 12 September 2026. Mohon siswa tetap di rumah & menjaga kesehatan • PPDB ONLINE TAHUN AJARAN 2026/2027 RESMI DIBUKA — Silakan daftarkan putra-putri Anda melalui menu PPDB Online di portal ini!',
    theme: 'warning',
    speed: 'normal',
    buttonEnabled: false,
    buttonText: '',
    buttonUrl: '',
    isMarquee: true,
    isSticky: true,
  },
  header: {
    heroTitle: 'Selamat Datang di Portal Resmi SMP Negeri 1 Bengkalis',
    heroSubtitle: 'Sekolah Menengah Pertama rujukan terdepan di Kabupaten Bengkalis yang berdedikasi melahirkan generasi berkarakter luhur, berprestasi akademik & non-akademik, serta menguasai sains dan teknologi.',
    heroImageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1600&auto=format&fit=crop&q=80',
    heroCtaText: 'Info PPDB & Pendaftaran',
    heroCtaLink: '#ppdb',
    secondaryCtaText: 'Profil & Prestasi Sekolah',
    secondaryCtaLink: '#profil',
    highlights: [
      { id: '1', icon: 'Award', label: 'Akreditasi Sekolah', value: 'Unggul (A)' },
      { id: '2', icon: 'GraduationCap', label: 'Kelulusan Siswa', value: '100% Lulus' },
      { id: '3', icon: 'Users', label: 'Peserta Didik', value: '850+ Siswa' },
      { id: '4', icon: 'BookOpen', label: 'Pendidik Profesional', value: '55+ Guru' },
    ],
  },
  navMenus: [
    {
      id: 'm1',
      label: 'Beranda',
      path: '#beranda',
      isDropdown: false,
      enabled: true,
    },
    {
      id: 'm2',
      label: 'Profil Sekolah',
      path: '#profil',
      isDropdown: true,
      enabled: true,
      dropdownItems: [
        { id: 'd2-1', label: 'Sambutan Kepala Sekolah', path: '#sambutan', description: 'Pesan hangat dari pimpinan SMPN 1 Bengkalis' },
        { id: 'd2-2', label: 'Visi & Misi', path: '#profil-visi', description: 'Arah, cita-cita, dan komitmen mutu pendidikan' },
        { id: 'd2-3', label: 'Fasilitas Belajar', path: '#fasilitas', description: 'Laboratorium IPA, Komputer, & Perpustakaan' },
        { id: 'd2-4', label: 'Video Profil Sekolah', path: '#video-profil', description: 'Tayangan dokumenter aktivitas sekolah' },
      ],
    },
    {
      id: 'm3',
      label: 'Kesiswaan & Ekskul',
      path: '#ekskul',
      isDropdown: true,
      enabled: true,
      dropdownItems: [
        { id: 'd3-1', label: 'Ekstrakurikuler', path: '#ekskul', description: 'Pramuka, PMR, Seni Musik Melayu, & Olahraga' },
        { id: 'd3-2', label: 'Prestasi Siswa', path: '#berita', description: 'Koleksi penghargaan tingkat kabupaten & provinsi' },
        { id: 'd3-3', label: 'OSIS SMPN 1', path: '#kesiswaan-osis', description: 'Organisasi Siswa Intra Sekolah' },
      ],
    },
    {
      id: 'm4',
      label: 'Berita & Info',
      path: '#berita',
      isDropdown: false,
      enabled: true,
    },
    {
      id: 'm5',
      label: 'Agenda Kegiatan',
      path: '#agenda',
      isDropdown: false,
      enabled: true,
    },
    {
      id: 'm6',
      label: 'Lokasi & Kontak',
      path: '#kontak',
      isDropdown: false,
      enabled: true,
    },
  ],
  layoutSections: {
    showHero: true,
    showQuickStats: true,
    showAccreditation: true,
    showPrincipalSpeech: true,
    showNews: true,
    showAgenda: true,
    showFacilities: true,
    showExtracurriculars: true,
    showVideoEmbed: true,
    showMapEmbed: true,
  },
  mobileBottomNav: {
    enabled: true,
    showHome: true,
    showNews: true,
    showAchievements: true,
    showExtracurriculars: true,
    showContact: true,
    styleVariant: 'floating-dock',
    themeColor: 'dark-slate',
    accentColor: 'blue',
    showLabels: false,
    elevatedCenterButton: true,
    showActiveIndicator: true,
  },
  principal: {
    name: '',
    title: 'Kepala Sekolah',
    nip: '',
    imageUrl: '',
    quote: '',
    fullSpeech: '',
  },
  ppdb: {
    enabled: false,
    buttonLabel: 'Info PPDB 2026',
    buttonLink: '#berita',
    openInNewTab: false,
    academicYear: '2026/2027',
    statusText: 'Pendaftaran Dibuka',
    badgeText: 'Tahun Ajaran 2026/2027',
    announcement: 'Penerimaan Peserta Didik Baru (PPDB) SMP Negeri 1 Bengkalis Tahun Ajaran 2026/2027 melalui jalur Zonasi, Afirmasi, Perpindahan Tugas Orang Tua, dan Prestasi.',
    contactPerson: '0812-7561-8899 (Panitia PPDB)',
    brochureUrl: '',
  },
  embeds: {
    youtubeTitle: 'Profil & Tur Lingkungan SMP Negeri 1 Bengkalis',
    youtubeSubtitle: 'Saksikan suasana belajar yang asri, sarana laboratorium, dan keceriaan siswa-siswi kami di Jl. Pertanian, Bengkalis Kota.',
    youtubeUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    mapTitle: 'Peta Lokasi SMP Negeri 1 Bengkalis (Jl. Pertanian)',
    mapIframeUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.6656729584407!2d102.1066!3d1.4727!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31d161d9a242c759%3A0xb3ef4a65ebae245b!2sBengkalis%2C%20Riau!5e0!3m2!1sid!2sid!4v1625580000000!5m2!1sid!2sid',
  },
  facilities: [
    {
      id: 'f1',
      title: 'Laboratorium IPA Terpadu',
      category: 'Akademik',
      imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=600&auto=format&fit=crop&q=80',
      description: 'Dilengkapi alat peraga Biologi dan Fisika lengkap untuk mendukung praktikum sains dan eksperimen siswa.',
    },
    {
      id: 'f2',
      title: 'Perpustakaan & Pojok Baca Digital',
      category: 'Literasi',
      imageUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=600&auto=format&fit=crop&q=80',
      description: 'Koleksi ribuan buku pelajaran, ensiklopedia, referensi bacaan umum, dan fasilitas komputer literasi digital.',
    },
    {
      id: 'f3',
      title: 'Laboratorium Komputer & Informatika',
      category: 'Teknologi',
      imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80',
      description: 'Ruang berpendingin udara dengan unit komputer modern untuk pembelajaran TIK, ANBK, dan coding dasar.',
    },
    {
      id: 'f4',
      title: 'Lapangan Olahraga & Seni Terbuka',
      category: 'Olahraga',
      imageUrl: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&auto=format&fit=crop&q=80',
      description: 'Sarana multifungsi untuk upacara bendera, bola voli, basket, futsal, dan kegiatan pentas seni sekolah.',
    },
  ],
  extracurriculars: [
    {
      id: 'e1',
      name: 'Pramuka Gugus Depan Bengkalis',
      category: 'Kepanduan',
      coach: 'Kak Ahmad Zulkarnain, S.Pd.',
      schedule: 'Jumat, 15:00 WIB',
      icon: 'Flag',
      description: 'Pembinaan kedisiplinan, kepemimpinan, keterampilan survival, dan bakti sosial kepanduan.',
    },
    {
      id: 'e2',
      name: 'Sanggar Seni & Musik Melayu',
      category: 'Seni & Budaya',
      coach: 'Nurul Hidayah, S.Sn.',
      schedule: 'Sabtu, 09:00 WIB',
      icon: 'Music',
      description: 'Melestarikan seni tari Melayu, kompang, vokal solo, dan seni musik tradisional khas Bengkalis.',
    },
    {
      id: 'e3',
      name: 'Palang Merah Remaja (PMR)',
      category: 'Kemanusiaan',
      coach: 'Ns. Rina Marlina, S.Kep.',
      schedule: 'Kamis, 15:30 WIB',
      icon: 'HeartHandshake',
      description: 'Pelatihan pertolongan pertama pada kecelakaan (P3K), donor darah, dan kebersihan lingkungan.',
    },
    {
      id: 'e4',
      name: 'Klub Sains & Olimpiade (OSN)',
      category: 'Sains & Riset',
      coach: 'Dedi Kurniawan, M.Pd.',
      schedule: 'Selasa & Kamis, 14:30 WIB',
      icon: 'Cpu',
      description: 'Bimbingan intensif persiapan Olimpiade Sains Nasional bidang Matematika, IPA, dan IPS.',
    },
    {
      id: 'e5',
      name: 'Futsal & Atletik Siswa',
      category: 'Olahraga',
      coach: 'Muhammad Yusuf, S.Pd.',
      schedule: 'Rabu & Sabtu, 16:00 WIB',
      icon: 'Trophy',
      description: 'Latihan fisik, teknik dasar permainan, sportivitas, dan kejuaraan tingkat O2SN Kabupaten Bengkalis.',
    },
    {
      id: 'e6',
      name: 'English Club & Storytelling',
      category: 'Bahasa & Komunikasi',
      coach: 'Siti Aminah, M.Ed.',
      schedule: 'Senin, 15:00 WIB',
      icon: 'MessageSquare',
      description: 'Mengasah kemampuan percakapan bahasa Inggris, pidato (speech), dan lomba bercerita (storytelling).',
    },
  ],
  agendas: [
    {
      id: 'a1',
      title: 'Pekan Asesmen Sumatif Akhir Semester',
      date: '08 - 15 Juni 2026',
      time: '07:30 - 12:00 WIB',
      location: 'Ruang Kelas & Lab Komputer',
      category: 'Akademik',
    },
    {
      id: 'a2',
      title: 'Gelar Karya Projek Profil Pelajar Pancasila (P5)',
      date: '20 Juni 2026',
      time: '08:00 - 14:00 WIB',
      location: 'Aula & Halaman SMPN 1 Bengkalis',
      category: 'Karya Siswa',
    },
    {
      id: 'a3',
      title: 'Sosialisasi Alur Pendaftaran PPDB Zonasi & Prestasi',
      date: '26 Juni 2026',
      time: '09:00 - 11:30 WIB',
      location: 'Aula Utama & Daring via Zoom',
      category: 'Informasi PPDB',
    },
  ],
  footer: {
    aboutText: 'SMP Negeri 1 Bengkalis adalah institusi pendidikan menengah pertama rujukan berakreditasi A di Kabupaten Bengkalis yang berdedikasi mendidik siswa berprestasi, berkarakter mulia, dan berwawasan lingkungan hidup.',
    address: 'Jl. Pertanian, Bengkalis Kota, Kec. Bengkalis, Kab. Bengkalis, Riau 28712',
    phone: '(0766) 21155',
    whatsapp: '+62 812-7654-3210',
    email: 'smpn1bengkalis@gmail.com',
    openingHours: 'Senin - Jumat: 07:00 - 15:30 WIB',
    socialLinks: {
      instagram: 'https://instagram.com/smpn1bengkalis',
      youtube: 'https://youtube.com/@smpn1bengkalis',
      facebook: 'https://facebook.com/smpn1bengkalis',
      twitter: 'https://x.com/smpn1bengkalis',
    },
    copyright: '© 2026 SMP Negeri 1 Bengkalis (NPSN: 10495146). Hak Cipta Dilindungi Undang-Undang.',
  },
  themeConfig: DEFAULT_THEME_CONFIG,
  googleAppsScript: {
    enabled: true,
    webAppUrl: DEFAULT_APPS_SCRIPT_WEB_APP_URL || '',
    folderId: DEFAULT_APPS_SCRIPT_FOLDER_ID || '',
    spreadsheetId: '',
    autoCreateFolder: true,
    testStatus: 'untested',
  },
};

// Empty default articles: all articles are loaded purely from Firebase and cache
export const DEFAULT_NEWS_ARTICLES: NewsArticle[] = [];
