import { SchoolConfig, NewsArticle } from '../types';
import { DEFAULT_THEME_CONFIG } from './themePresets';
import { DEFAULT_APPS_SCRIPT_WEB_APP_URL, DEFAULT_APPS_SCRIPT_FOLDER_ID } from './googleAppsScript';

export const DEFAULT_SCHOOL_CONFIG: SchoolConfig = {
  adminPassword: '',
  identity: {
    name: '',
    shortName: '',
    tagline: '',
    npsn: '',
    akreditasi: '',
    logoUrl: 'https://i.ibb.co.com/d44hK88L/logo-smpn-1-bengkalis-kecil.png',
    faviconUrl: 'https://i.ibb.co.com/d44hK88L/logo-smpn-1-bengkalis-kecil.png',
    tickerEnabled: false,
    tickerText: '',
    accreditationTickerEnabled: false,
    accreditationTickerText: '',
    accreditationTickerSpeed: 'normal',
    primaryColor: 'blue',
  },
  importantAnnouncement: {
    enabled: false,
    badge: 'PENGUMUMAN',
    text: '',
    theme: 'info',
    speed: 'normal',
    buttonEnabled: false,
    buttonText: '',
    buttonUrl: '',
    isMarquee: true,
    isSticky: true,
  },
  header: {
    heroTitle: '',
    heroSubtitle: '',
    heroImageUrl: '',
    heroCtaText: '',
    heroCtaLink: '',
    secondaryCtaText: '',
    secondaryCtaLink: '',
    highlights: [],
  },
  navMenus: [],
  layoutSections: {
    showHero: true,
    showQuickStats: false,
    showAccreditation: false,
    showPrincipalSpeech: true,
    showNews: true,
    showAgenda: false,
    showFacilities: false,
    showExtracurriculars: false,
    showVideoEmbed: false,
    showMapEmbed: false,
  },
  mobileBottomNav: {
    enabled: true,
    showHome: true,
    showNews: true,
    showAchievements: false,
    showExtracurriculars: false,
    showContact: true,
    styleVariant: 'floating-dock',
    themeColor: 'dark-slate',
    accentColor: 'blue',
    showLabels: false,
    elevatedCenterButton: true,
    showActiveIndicator: true,
  },
  principal: {
    name: '',
    title: '',
    nip: '',
    imageUrl: '',
    quote: '',
    fullSpeech: '',
  },
  ppdb: {
    enabled: false,
    buttonLabel: '',
    buttonLink: '',
    openInNewTab: false,
    academicYear: '',
    statusText: '',
    badgeText: '',
    announcement: '',
    contactPerson: '',
    brochureUrl: '',
  },
  embeds: {
    youtubeTitle: '',
    youtubeSubtitle: '',
    youtubeUrl: '',
    mapTitle: '',
    mapIframeUrl: '',
  },
  facilities: [],
  extracurriculars: [],
  agendas: [],
  footer: {
    aboutText: '',
    address: '',
    phone: '',
    whatsapp: '',
    email: '',
    openingHours: '',
    socialLinks: {
      instagram: '',
      youtube: '',
      facebook: '',
      twitter: '',
    },
    copyright: '',
  },
  themeConfig: DEFAULT_THEME_CONFIG,
  googleAppsScript: {
    enabled: true,
    webAppUrl: DEFAULT_APPS_SCRIPT_WEB_APP_URL || '',
    folderId: DEFAULT_APPS_SCRIPT_FOLDER_ID || '',
    spreadsheetId: '',
    autoCreateFolder: true,
    testStatus: 'untested',
  },
};

// Empty default articles: all articles are loaded purely from Firebase and cache
export const DEFAULT_NEWS_ARTICLES: NewsArticle[] = [];

