import { MobileBottomNavConfig } from '../types';

export interface DockPreset {
  id: string;
  name: string;
  category: 'floating' | 'full-bottom';
  description: string;
  config: Partial<MobileBottomNavConfig>;
  preview: {
    bgClass: string;
    borderClass: string;
    centerButtonClass: string;
    centerShape: 'circle' | 'rounded-square' | 'diamond' | 'pill';
    iconColor: string;
    accentGlowColor: string;
  };
}

export const DOCK_PRESETS: DockPreset[] = [
  // --- KELOMPOK 1: MENUTUPI AREA BAWAH (FULL-WIDTH BOTTOM BAR) ---
  {
    id: 'full-dark-glass',
    name: 'Full Bar Dark Glass (Menutupi Bawah)',
    category: 'full-bottom',
    description: 'Menutupi area bawah layar penuh (edge-to-edge) bernuansa kaca gelap dengan tombol tengah melayang bercahaya',
    config: {
      positionMode: 'full-bottom',
      styleVariant: 'glass-bar',
      themeColor: 'dark-slate',
      accentColor: 'blue',
      centerButtonShape: 'circle',
      elevatedCenterButton: true,
      glowEffect: true,
      showActiveIndicator: true,
    },
    preview: {
      bgClass: 'bg-slate-900/98',
      borderClass: 'border-t border-slate-700/80',
      centerButtonClass: 'bg-gradient-to-tr from-blue-600 to-indigo-600 text-white shadow-blue-500/50',
      centerShape: 'circle',
      iconColor: 'text-blue-400',
      accentGlowColor: '#3b82f6',
    },
  },
  {
    id: 'full-white-glass',
    name: 'Full Bar Modern White (Menutupi Bawah)',
    category: 'full-bottom',
    description: 'Bilah penuh bawah layar warna putih bersih dengan garis batas atas halus dan tombol biru menonjol',
    config: {
      positionMode: 'full-bottom',
      styleVariant: 'glass-bar',
      themeColor: 'light-modern',
      accentColor: 'blue',
      centerButtonShape: 'circle',
      elevatedCenterButton: true,
      glowEffect: true,
      showActiveIndicator: true,
    },
    preview: {
      bgClass: 'bg-white/98',
      borderClass: 'border-t border-slate-200 shadow-lg',
      centerButtonClass: 'bg-gradient-to-tr from-blue-600 to-blue-500 text-white shadow-blue-500/40',
      centerShape: 'circle',
      iconColor: 'text-blue-600',
      accentGlowColor: '#2563eb',
    },
  },
  {
    id: 'full-notch-dark',
    name: 'Full Bar Curved Wave Dark (Menutupi Bawah)',
    category: 'full-bottom',
    description: 'Bilah penuh menutupi bawah dengan lekukan gelombang halus (wave notch) pada tombol tengah',
    config: {
      positionMode: 'full-bottom',
      styleVariant: 'curved-notch',
      themeColor: 'deep-navy',
      accentColor: 'cyan',
      centerButtonShape: 'circle',
      elevatedCenterButton: true,
      glowEffect: true,
      showActiveIndicator: true,
    },
    preview: {
      bgClass: 'bg-slate-950',
      borderClass: 'border-t border-slate-800',
      centerButtonClass: 'bg-gradient-to-tr from-cyan-500 to-blue-600 text-white shadow-cyan-500/50',
      centerShape: 'circle',
      iconColor: 'text-cyan-400',
      accentGlowColor: '#06b6d4',
    },
  },
  {
    id: 'full-notch-white',
    name: 'Full Bar Curved Wave White (Menutupi Bawah)',
    category: 'full-bottom',
    description: 'Bilah penuh putih menutupi bawah dengan lekukan kurva melengkung pada tombol home hijau toska',
    config: {
      positionMode: 'full-bottom',
      styleVariant: 'curved-notch',
      themeColor: 'light-modern',
      accentColor: 'emerald',
      centerButtonShape: 'circle',
      elevatedCenterButton: true,
      glowEffect: true,
      showActiveIndicator: true,
    },
    preview: {
      bgClass: 'bg-white',
      borderClass: 'border-t border-slate-200',
      centerButtonClass: 'bg-gradient-to-tr from-emerald-500 to-teal-600 text-white shadow-emerald-500/40',
      centerShape: 'circle',
      iconColor: 'text-emerald-600',
      accentGlowColor: '#10b981',
    },
  },

  // --- KELOMPOK 2: FLOATING DOCK (MELAYANG) ---
  {
    id: 'cyber-navy',
    name: 'Cyber Navy Neon (Melayang)',
    category: 'floating',
    description: 'Docker melayang gelap pekat dengan tombol tengah berpendar cahaya biru neon modern',
    config: {
      positionMode: 'floating',
      styleVariant: 'minimal-pill',
      themeColor: 'deep-navy',
      accentColor: 'blue',
      centerButtonShape: 'circle',
      elevatedCenterButton: true,
      glowEffect: true,
      showActiveIndicator: true,
    },
    preview: {
      bgClass: 'bg-slate-950/95',
      borderClass: 'border border-blue-900/80',
      centerButtonClass: 'bg-gradient-to-tr from-blue-600 to-indigo-500 text-white shadow-blue-500/60 ring-2 ring-blue-400/40',
      centerShape: 'circle',
      iconColor: 'text-blue-400',
      accentGlowColor: '#3b82f6',
    },
  },
  {
    id: 'white-minimal-glow',
    name: 'Pure White Minimal Pill (Melayang)',
    category: 'floating',
    description: 'Bentuk kapsul putih bersih melayang dengan tombol tengah lingkaran biru bercahaya lembut',
    config: {
      positionMode: 'floating',
      styleVariant: 'minimal-pill',
      themeColor: 'light-modern',
      accentColor: 'blue',
      centerButtonShape: 'circle',
      elevatedCenterButton: true,
      glowEffect: true,
      showActiveIndicator: true,
    },
    preview: {
      bgClass: 'bg-white/95',
      borderClass: 'border border-slate-200/90 shadow-xl',
      centerButtonClass: 'bg-blue-600 text-white shadow-blue-500/50',
      centerShape: 'circle',
      iconColor: 'text-blue-600',
      accentGlowColor: '#2563eb',
    },
  },
  {
    id: 'emerald-forest-glow',
    name: 'Emerald Forest Glow (Melayang)',
    category: 'floating',
    description: 'Docker gelap dengan tombol hijau zamrud menyala melingkar (cocok untuk tema sekolah alam/Islami)',
    config: {
      positionMode: 'floating',
      styleVariant: 'floating-dock',
      themeColor: 'emerald-green',
      accentColor: 'emerald',
      centerButtonShape: 'circle',
      elevatedCenterButton: true,
      glowEffect: true,
      showActiveIndicator: true,
    },
    preview: {
      bgClass: 'bg-emerald-950/95',
      borderClass: 'border border-emerald-800/80',
      centerButtonClass: 'bg-gradient-to-tr from-emerald-500 to-teal-500 text-white shadow-emerald-500/60 ring-2 ring-emerald-400/30',
      centerShape: 'circle',
      iconColor: 'text-emerald-400',
      accentGlowColor: '#10b981',
    },
  },
  {
    id: 'pastel-rose-soft',
    name: 'Sweet Pastel Rose (Melayang)',
    category: 'floating',
    description: 'Nuansa lembut pink pastel dengan tombol tengah pink magenta rounded-square yang manis',
    config: {
      positionMode: 'floating',
      styleVariant: 'minimal-pill',
      themeColor: 'pastel-pink',
      accentColor: 'rose',
      centerButtonShape: 'rounded-square',
      elevatedCenterButton: true,
      glowEffect: true,
      showActiveIndicator: true,
    },
    preview: {
      bgClass: 'bg-pink-50/95',
      borderClass: 'border border-pink-200 shadow-md',
      centerButtonClass: 'bg-gradient-to-tr from-pink-500 to-rose-600 text-white shadow-pink-500/50',
      centerShape: 'rounded-square',
      iconColor: 'text-pink-600',
      accentGlowColor: '#f43f5e',
    },
  },
  {
    id: 'ocean-gradient-bar',
    name: 'Ocean Gradient Wave (Melayang)',
    category: 'floating',
    description: 'Bilah bergradasi biru samudra ke ungu dengan tombol tengah kotak membulat putih/biru',
    config: {
      positionMode: 'floating',
      styleVariant: 'floating-dock',
      themeColor: 'ocean-gradient',
      accentColor: 'blue',
      centerButtonShape: 'rounded-square',
      elevatedCenterButton: true,
      glowEffect: true,
      showActiveIndicator: false,
    },
    preview: {
      bgClass: 'bg-gradient-to-r from-sky-500 via-blue-600 to-indigo-600',
      borderClass: 'border border-white/20 text-white',
      centerButtonClass: 'bg-white text-blue-600 shadow-lg',
      centerShape: 'rounded-square',
      iconColor: 'text-white',
      accentGlowColor: '#38bdf8',
    },
  },
  {
    id: 'diamond-accent-forest',
    name: 'Diamond Badge Green (Melayang)',
    category: 'floating',
    description: 'Docker hijau pekat dengan tombol tengah berbentuk berlian (Diamond 45° badge)',
    config: {
      positionMode: 'floating',
      styleVariant: 'minimal-pill',
      themeColor: 'emerald-green',
      accentColor: 'emerald',
      centerButtonShape: 'diamond',
      elevatedCenterButton: true,
      glowEffect: true,
      showActiveIndicator: true,
    },
    preview: {
      bgClass: 'bg-slate-900/95',
      borderClass: 'border border-emerald-700/70',
      centerButtonClass: 'bg-gradient-to-tr from-emerald-600 to-teal-500 text-white shadow-emerald-500/60',
      centerShape: 'diamond',
      iconColor: 'text-emerald-400',
      accentGlowColor: '#10b981',
    },
  },
  {
    id: 'sunset-amber-glow',
    name: 'Sunset Gold Orb (Melayang)',
    category: 'floating',
    description: 'Docker slate gelap dengan tombol emas kuning amber bercahaya hangat seperti lampu pijar',
    config: {
      positionMode: 'floating',
      styleVariant: 'floating-dock',
      themeColor: 'dark-slate',
      accentColor: 'amber',
      centerButtonShape: 'circle',
      elevatedCenterButton: true,
      glowEffect: true,
      showActiveIndicator: true,
    },
    preview: {
      bgClass: 'bg-slate-900/95',
      borderClass: 'border border-slate-700/80',
      centerButtonClass: 'bg-gradient-to-tr from-amber-500 to-orange-500 text-white shadow-amber-500/60 ring-2 ring-amber-400/30',
      centerShape: 'circle',
      iconColor: 'text-amber-400',
      accentGlowColor: '#f59e0b',
    },
  },
  {
    id: 'royal-purple-glow',
    name: 'Royal Purple Glow (Melayang)',
    category: 'floating',
    description: 'Docker ungu violet dengan tombol tengah ungu neon mempesona',
    config: {
      positionMode: 'floating',
      styleVariant: 'floating-dock',
      themeColor: 'royal-indigo',
      accentColor: 'purple',
      centerButtonShape: 'circle',
      elevatedCenterButton: true,
      glowEffect: true,
      showActiveIndicator: true,
    },
    preview: {
      bgClass: 'bg-indigo-950/95',
      borderClass: 'border border-purple-800/80',
      centerButtonClass: 'bg-gradient-to-tr from-purple-600 to-fuchsia-600 text-white shadow-purple-500/60',
      centerShape: 'circle',
      iconColor: 'text-purple-400',
      accentGlowColor: '#a855f7',
    },
  },
  {
    id: 'sunset-magenta-fade',
    name: 'Sunset Magenta Fade (Melayang)',
    category: 'floating',
    description: 'Bilah hitam dengan aksen gradasi merah muda ke ungu magenta yang artistik',
    config: {
      positionMode: 'floating',
      styleVariant: 'floating-dock',
      themeColor: 'sunset-magenta',
      accentColor: 'rose',
      centerButtonShape: 'rounded-square',
      elevatedCenterButton: true,
      glowEffect: true,
      showActiveIndicator: true,
    },
    preview: {
      bgClass: 'bg-slate-950/95',
      borderClass: 'border border-pink-900/60',
      centerButtonClass: 'bg-gradient-to-tr from-pink-600 to-purple-600 text-white shadow-pink-500/50',
      centerShape: 'rounded-square',
      iconColor: 'text-pink-400',
      accentGlowColor: '#ec4899',
    },
  },
  {
    id: 'clean-outline-slate',
    name: 'Modern Flat Slate (Melayang)',
    category: 'floating',
    description: 'Gaya flat datar minimalis tanpa tombol menonjol, rata sejajar dengan garis bersih',
    config: {
      positionMode: 'floating',
      styleVariant: 'minimal-pill',
      themeColor: 'dark-slate',
      accentColor: 'blue',
      centerButtonShape: 'flat',
      elevatedCenterButton: false,
      glowEffect: false,
      showActiveIndicator: true,
    },
    preview: {
      bgClass: 'bg-slate-900/90',
      borderClass: 'border border-slate-700/70',
      centerButtonClass: 'bg-slate-800 text-blue-400',
      centerShape: 'pill',
      iconColor: 'text-slate-400',
      accentGlowColor: '#3b82f6',
    },
  },
];
